/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.mycompany.nycrosswordpuzzle.Cell;

/**
 *
 * @author kaan
 */
public class CellGUI extends javax.swing.JPanel {
    
    private final String correctWord;
    private String currentWord;
    private final int cellNo;
    private final boolean isBlock;
    private final int downClue;
    private final int acrossClue;
    private final Cell c;

    /**
     * Creates new form Cell
     * @param c
     */
    public CellGUI( Cell c ) {
        
        this.c = c;
        this.cellNo = c.getCellNo();
        this.correctWord = c.getCorrectWord();
        this.currentWord = c.getCorrectWord();
        this.isBlock = c.isIsBlock();
        this.downClue = c.getDownClue();
        this.acrossClue = c.getAcrossClue();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clueNum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        answerText = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 255, 255));

        clueNum.setEditable(false);
        clueNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clueNum.setText(c.getCellNo() + "");
        clueNum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clueNum.setEnabled(false);

        answerText.setBackground(new java.awt.Color(255, 255, 255));
        answerText.setBorder(null);
        answerText.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        answerText.setCaretColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(answerText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(clueNum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(clueNum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane answerText;
    private javax.swing.JTextField clueNum;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
