/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;

/**
 *
 * @author kaan
 */
public class MainBoard extends javax.swing.JPanel {

    /**
     * Creates new form MainBoard
     * @param width
     * @param cellGUIs
     */
    public MainBoard( int width, ArrayList<CellGUI> cellGUIs ) {
        initComponents();
        setGrid( width );
        addCells( cellGUIs );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board = new javax.swing.JPanel();
        groupNameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        board.setLayout(new java.awt.GridLayout());

        groupNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        groupNameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        groupNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        groupNameLabel.setText("SOLVER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(groupNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void setGrid( int width ) {
        board.setLayout( new java.awt.GridLayout( width, width ) );
    }

    private void addCells( ArrayList<CellGUI> cells ) {
        cells.forEach( ( c ) -> {
            board.add( (CellGUI) c );
        } );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel board;
    private javax.swing.JLabel groupNameLabel;
    // End of variables declaration//GEN-END:variables
}
